# Generated by Django 3.2.11 on 2022-01-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, null=True, verbose_name='path')),
                ('detected_path', models.CharField(max_length=255, null=True, verbose_name='detected_path')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/')),
                ('detected_image_file', models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/detected/')),
            ],
        ),
    ]
