# Generated by Django 3.2.11 on 2022-01-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_detector_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='detected_output_image_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/%d_%m_%Y_%H_%M_%S/detected_output/'),
        ),
        migrations.AddField(
            model_name='image',
            name='output_path',
            field=models.CharField(max_length=255, null=True, verbose_name='output_path'),
        ),
    ]
