# Generated by Django 3.2.11 on 2022-01-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lai_detector_app', '0002_auto_20220129_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='FVC',
            field=models.FloatField(blank=True, null=True, verbose_name='FVC'),
        ),
        migrations.AddField(
            model_name='image',
            name='LAI',
            field=models.FloatField(blank=True, null=True, verbose_name='LAI'),
        ),
        migrations.AddField(
            model_name='image',
            name='Latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='image',
            name='Longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='image',
            name='X',
            field=models.FloatField(blank=True, null=True, verbose_name='X'),
        ),
        migrations.AddField(
            model_name='image',
            name='Y',
            field=models.FloatField(blank=True, null=True, verbose_name='Y'),
        ),
    ]
